#
#    Cached file of:
#    A 2-d array the same size as the image (in pixels) specifying
#    that pixel (i,j) belongs to cell c where c is a non-negative integer.
#    If c = 0 it means that the associated pixel does not belong to a cell
#
DEFAULT:
    LABEL_IMAGE: 'data/default/CellMap.mat'



#
#    Cached file with:
#     1. number of genes
#     2. number of cells
#     3. gene expression table (size: numGenes by numCells)
#     4. gene names (vector of length numGenes)
#     5. class name that each cell belongs to (vector of length numCells)
#
geneset: '../data/GeneSet.mat'



#
#    Parameters for the Cell calling algorithm
#
CellCallMaxIter: 100
CellCallTolerance: 0.02
Inefficiency: 0.2
InsideCellBonus: 2
MisreadDensity: 0.00001
SpotReg: 0.1
nNeighbors: 3
rGene: 20
rSpot: 2




#
#    Specify the area we are interested in. This is used as filter to ignore spots outside the area.
#    Not the whole polygon needs to be specified in a real life example.
#    The bottom left corner however needs to get passed in
#
CellCallRegionYX: !2darray
  - - 17268
    - 13751
  - - 15629
    - 12739
  - - 16237
    - 11839
  - - 16528
    - 11120
  - - 16396
    - 10333
  - - 16105
    - 9906
  - - 15603
    - 9231
  - - 15286
    - 8916
  - - 12987
    - 6263
  - - 13648
    - 6150
  - - 14282
    - 6150
  - - 15074
    - 6420
  - - 15735
    - 6735
  - - 16369
    - 7072
  - - 16977
    - 7522
  - - 17637
    - 8264
  - - 18113
    - 9119
  - - 18324
    - 10130
  - - 18457
    - 10872
  - - 18298
    - 11997
  - - 17981
    - 12626
  - - 17479
    - 13233
  - - 17268
    - 13751

